# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'changeLocation' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for changeLocation
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'


  target 'changeLocationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'changeLocationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
